### ISSUE TITLE
Problem with example config

### ISSUE THREAD

**Issue by Balssh** [InioX/matugen#38]
Hi there, was trying out this tool and I think the example config is broken as I try to run it and I get the following error:

```
matugen image ~/Projects/dotfiles/ags/assets/space.jpg

Error: 
   0: render error

         --> name1:28:36
          |
       28 | @define-color source_color {{colors.source_color.default.hex}};;
          |                                    ^^^^^^^^^^^^^
          |
          = reason: not found in map
   0: 
   1: render error: not found in map

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by InioX** [comment]
Hi, @Balssh !

What version of Matugen are you on? The config should only work from the https://github.com/InioX/matugen/commit/662f285def4b153d88f74132c8bd7158117fa6ce commit and further, as it hasn't made it into a release yet.

**Comment by Balssh** [comment]
I'm on 1.1.1, installed using cargo. It's weird that only that specific line is buggy, if I comment it out it seems to be working.

**Comment by InioX** [comment]
The config and template in `example/` folder only work if you compile matugen yourself on the latest git commit, because the commit that makes the template work is not released yet. Check out the files in the [matugen-v1.1.1](https://github.com/InioX/matugen/tree/matugen-v1.1.1) tag and it will work.
